apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::063023240456:role/UdacityFlaskDeployCBKubectlRole
      username: build   
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::063023240456:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1R8E0GA8RLM9P
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-11T12:15:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1555"
  uid: 6caf84bb-4640-4d47-8644-11b4d9037872
